#!/usr/bin/ruby
$LOAD_PATH.unshift('.')

current_branch = `git rev-parse --abbrev-ref HEAD`.strip
required_branch = 'main'
if current_branch != required_branch
  puts "WARNING: Not on #{ required_branch } branch (on #{current_branch}), cannot release."
  abort
end

def increment(filename, current_branch)
    # Read it
    file_str = ''
    if File.exist?(filename)
        file_str = File.open(filename, 'r') {|file| file.read }
    end

    new_version = file_str.gsub(/([\"\']\d+\.\d+\.)(\d+)([\"\'])/) do |match|

      $1 + ($2.to_i+1).to_s + $3
    end

    # Write
    File.open(filename, 'w') {|file| file.write(new_version) }

    version_string = /[\"\'](.*)[\"\']/.match(new_version)[1]

    puts "Incrementing version number in #{filename} to #{version_string}"

    puts `git add #{filename}`
    puts `git commit -m "Automatic: incrementing version (#{version_string})"`
    puts `git tag v#{version_string}`
    puts `git push origin #{current_branch}`
    puts `git push --tags origin #{current_branch}`
end

increment('lib/video_embed/version.rb', current_branch)
require 'lib/video_embed/version'

puts `gem build video_embed.gemspec`
puts `curl -F package=@video_embed-#{ VideoEmbed::VERSION }.gem https://push.fury.io/4RqtDs9ewSz9NeiBtxLL/`
